[package]
name = "bevy_streamdeck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.6", default-features = false, features = [ "bevy_render" ] }
streamdeck = { version = "0.6", default-features = false }
crossbeam-channel = "0.5"
image = "0.23"

[dev-dependencies]
rand = "0.8"

[patch.crates-io]
streamdeck = { git = "https://github.com/mockersf/rust-streamdeck", branch = "mini-key-count" }
