[package]
name = "bevy_streamdeck"
version = "0.1.0"
edition = "2021"
authors = ["François Mockers <mockersf@gmail.com>"]
description = "Elgato Stream Deck plugin for Bevy"
repository = "https://github.com/vleue/bevy_streamdeck"
homepage = "https://github.com/vleue/bevy_streamdeck"
documentation = "https://docs.rs/bevy_streamdeck"
keywords = ["bevy", "streamdeck"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[features]
default = [ "color_compatibility", "image_compatibility" ]
color_compatibility = [ "bevy_render" ]
image_compatibility = [ "bevy_render", "images" ]
images = [ "image" ]

[dependencies]
bevy_ecs = { version = "0.6" }
bevy_app = { version = "0.6" }
bevy_input = { version = "0.6" }
bevy_log = { version = "0.6" }
bevy_tasks = { version = "0.6" }
streamdeck = { version = "0.6", default-features = false }
crossbeam-channel = "0.5"
bevy_render = { version = "0.6", optional = true }
image = { version = "0.24", optional = true }

[dev-dependencies]
rand = "0.8"
bevy_core = { version = "0.6" }
bevy = { version = "0.6" }

[[example]]
name = "image"

