[package]
name = "bevy_streamdeck"
version = "0.1.0"
edition = "2021"
authors = ["François Mockers <mockersf@gmail.com>"]
description = "Elgato Stream Deck plugin for Bevy"
repository = "https://github.com/vleue/bevy_streamdeck"
homepage = "https://github.com/vleue/bevy_streamdeck"
documentation = "https://docs.rs/bevy_streamdeck"
keywords = ["bevy", "streamdeck"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
bevy = { version = "0.6", default-features = false, features = [ "bevy_render" ] }
streamdeck = { version = "0.6", default-features = false }
crossbeam-channel = "0.5"
image = "0.23"

[dev-dependencies]
rand = "0.8"

[[example]]
name = "image"
required-features = [ "bevy/png" ]

